__path = process.cwd()
module.exports = async (md, m, fetchJson, bot, type, body, budy, prefix, isCommand, command, isGroup, md1, pushname, q, args, content, sender, from, nama, namabot, owner, reply, donasi, isMedia, isQuotedImage, isQuotedVideo, isQuotedSticker, isQuotedAudio) => {  
try{  

var gombal = [
"Seperti aku harus mengikhlaskanmu. Sedangkan kamu pernah menjadi milik ku.",
"Ada kesadaran dalam diamku. Ada penghargaan dalam teriakku, tapi tetap saja ada yang pergi meninggalkanku.",
"Bodohnya aku masih merasa cemburu, ketika melihatmu dengan kekasih yang baru.",
"Semua bisa berakhir, orang berubah. Dan kamu tahu apa? Hidup kan terus berjalan.",
"Setelah kamu pergi, aku menjadi sadar bahwa orang baik akan bersanding dengan orang yang baik pula.",
"Aku lebih suka lengan yang patah daripada patah hati. - Christie Brinkley",
"Mungkin kebahagiaan bersamamu hanya seperti mimpi, tapi biarlah mimpi itu terus menemani di setiap tidurku.",
"Ada rasa jenuh saat bertahan, namun ada sakit saat meninggalkan.",
"Kamu adalah patah hati terbaik yang tak akan pernah aku sesali.",
"Aku hanya ingin cinta yang sederhana. Cintai aku tanpa batas rasa sayang. Menetaplah jangan hanya sebatas menemani.",
"Cinta tapi tak dianggap itu seperti sakit tapi tak berdarah.",
"Aku tahu yang kau cinta bukan aku. Tapi meskipun terluka, bolehkah aku tetap mencintaimu?",
"Buatlah aku bisa membencimu walau hanya beberapa menit, agar tidak terlalu berat untuk melupakanmu.",
"Aku tidak tahu apa itu cinta, sampai akhirnya aku bertemu denganmu. Tapi, saat itu juga aku tahu rasanya patah hati.",
"Semua menjadi sebuah kisah perjalanan dalam hidupku, dan tak sepantasnya aku merebutmu lagi dari dirinya.",
"Padahal hujan belum sempat menyambangi bumi, namun rintiknya telah membasahi pipi, hingga menusuk dalam relung hati.",
"Kau yang terbaik, juga terburuk. Kau yang mengajari arti patah hati. Kau beri harap, lalu kau pergi. Garis waktu takkan mampu menghapusmu. - Fiersa Besari",
"Hati yang patah hanyalah rasa sakit yang tumbuh yang diperlukan agar kamu bisa lebih mencintai ketika hal yang sebenarnya terjadi. - J.S.B.Morse",
"Jadi inilah yang terjadi dengan hati yang hancur. Tidak peduli bagaimana Anda mencoba, potongan-potongan itu tidak pernah cocok seperti sebelumnya. – Ariana",
"Tidak ada yang bisa menghilangkan rasa selai kacang seperti cinta yang bertepuk sebelah tangan. - Charles M. Schulz",
"Cinta ditolak adalah bagian dari hidup. Itu akan berlalu jika kamu melepaskannya. Jadi, move on dan jalani hidupmu lagi.",
"Kamu tidak hanya menduakanku, tapi kita. Kamu tidak hanya menghancurkan hatiku, tapi merusak masa depan kita.",
"Coba kamu yang berada di posisiku, lalu kamu ditinggalin gitu aja sama orang yang lo sayang banget.",
"Luka terdalam adalah ketika kamu tak mampu melihat dengan mata, dan kesedihan terpendam adalah ketika kamu tak mampu mengucapkan dengan kata-kata.",
"Dulu kamu mendefinisikanmu sebagai cinta satu-satunya. Namun kini setelah bertemu dengan dia, definisimu tentang 'cinta satu-satunya' telah berubah makna.",
"Semua bisa berakhir, orang berubah. Dan kamu tahu apa? Hidup kan terus berjalan.",
"Musuhku adalah mereka yang ingin memilikimu juga.",
"Hatiku hancur berkeping-keping ketika ku jatuhkan padamu, namun kau berlalu dengan sengaja.",
"Kita memulai kisah berdua, tapi mengakhirinya bertiga.",
"Berharap agar aku dapat mengulang waktu agar aku tidak tahu kalau menyayangimu itu akan terasa sesakit ini.",
"Ketika seseorang yang kamu perjuangkan justru malah sebaliknya, percayalah ada orang yang lebih tepat di sana menunggu kamu melepaskannya.",
"Semakin punggungku diterpa hujan, semakin bayangmu terngiang-ngiang, dan semakin dalam kau cabik hati ini secara diam-diam.",
"Aku tak mungkin menyesali perkenalan kita, namun yang aku sesalkan kenapa terlalu awal untuk mengenal kata berpisah.",
"Ada kesadaran dalam diamku. Ada penghargaan dalam teriakku, tapi tetap saja ada yang pergi meninggalkanku.",
"Hilangmu kini tak lagi menarik perhatianku. Sebab aku sadar, harusnya jika kau sayang yang kau pilih adalah pulang, bukan hilang. - Boy Chandra",
"Ada beragam kata-kata sad boy yang kecewa karena pujaannya mungkin merespon perasaan cinta dan sayang tidak sesuai keinginannya. Nah lewat kata-kata sad boy yang kecewa di bawah ini bisa membuat kalian terharu akan perasaannya mereka.",
"Aku baru sadar, ternyata bersikap bodoh amat itu lebih menyenangkan daripada peduli tapi tidak dihargai.",
"Sakit hati ini sudah mulai terasa, setelah lama aku memendam perasaan sedih dan kecewa.",
"Bukannya tak pantas buat ditunggu, hanya saja sering memberi harapan palsu.",
"Cuek, pasti sakit, dikecewakan pasti sedih. Namun, ditinggal pergi tanpa alasan sungguh merana.",
"Setelah kamu pergi, aku menjadi sadar bahwa orang baik akan bersanding dengan orang yang baik pula.",
"Aku hanyalah daun yang jatuh dengan terpaksa, karena terlepas dari ranting yang lama menjadi sandaran.",
"Apakah salah jika kita berdoa meminta untuk dihilangkan ingatan kita akan segalanya.",
"Tiba-tiba saja kau menghilang. Ataukah aku yang memang tidak pernah membalas semua sapaanmu.",
"Tersenyum bukan berarti bahagia, namun terkadang itulah cara terbaik untuk menyembunyikan hati yang sedang terluka.",
"Terkadang kita tidak sadar sedang berharap kepada orang yang tidak bisa diharapkan.",
"Kita sering lupa bagaimana untuk bahagia karena kita sendiri lebih senang berteman dengan luka dan kecewa.",
"Melanjutkan hidup kembali itu mudah, yang sulit adalah meninggalkan masa lalu.",
"Ada waktu untuk berharap, dan ada waktu untuk berhenti. Ada masa untuk memperjuangkan, namun ada juga untuk mengikhlaskan.",
"Jangan buat aku terlalu berharap jika kamu tidak menginginkanku.",
"Jangan terlalu berharap pada seseorang, karena ketika dia tak mampu memenuhi harapanmu, kekecewaan akan hiasi harimu.",
"Hal yang paling menyakitkan adalah mencintai seseorang yang tak bisa bersamamu.",
"Aku terlalu bersahabat dengan luka hingga lupa rasanya bahagia.",
"Kisah cinta orang lain kayak es krim paddle pop rainbow, kisah cintaku kayak es batu, tawar dingin dan keras.",
"Sungguh aneh betapa seringnya hati harus hancur sebelum bertahun-tahun membuatnya menjadi bijak. - Sara Teasdale",
"Kesenangan cinta berlangsung sebentar. Rasa sakit cinta berlangsung seumur hidup. - Bette Davis",
"Mungkin suatu hari saya akan merangkak kembali ke rumah, dipukuli, dikalahkan. Tapi, tidak selama aku bisa membuat cerita dari kesedihan hatiku, keindahan dari duka. - Sylvia Plath",
"Aku rela menunggu meski kamu tak memberiku kabar. Bahkan aku sadar jika kamu ingin kamu tinggalkan.",
"Semenjak aku berhenti berharap pada dirimu, aku jadi tidak semangat dalam segala hal.",
"Kalaupun aku jatuh cinta dengan orang lain, perasaan itu tidak akan pernah sama ketika aku mencintaimu.",
"Aku hanya penikmat senyumanmu, bukan pemilik, apalagi penyebab.",
"Mungkin, kita sepenggal kisah yang lupa ditamatkan oleh penulisnya. Lalu, terkubur waktu hingga membuat tokoh utama terjebak kenangan.",
"Kamu benar-benar mencintai seseorang ketika kamu tidak bisa membencinya meskipun ia telah menyakitimu.",
"Mencintaimu dalam waktu yang lama tentu aku bisa, namun kehilanganmu sebentar saja sungguh berat rasanya.",
"Aku ingin mengatakan bahwa aku merindukanmu. Tapi, itu tidak akan mengubah apapun. Jadi, aku hanya memendamnya dan berpura-pura tidak merindukanmu.",
"Kamu pergi membawa kenangan, dan kamu datang kembali membawa undangan.",
"Sampai detik ini kamu masih menjadi alasan kenapa hatiku belum mau menerima siapa pun.",
"Mungkin memang aku yang harus mengerti bila aku bukan yang ingin kau miliki. Salahkah aku bila kaulah yang ada di hatiku."
]

md.sendMessage(from, { text: gombal[Math.floor(Math.random() * gombal.length)], mentions: [sender]}, {quoted: md1})
} catch (e) { console.log(e) }
} 
