__path = process.cwd()
module.exports = async (md, m, fetchJson, bot, type, body, budy, prefix, isCommand, command, isGroup, md1, pushname, q, args, content, sender, from, nama, namabot, owner, reply, donasi, isMedia, isQuotedImage, isQuotedVideo, isQuotedSticker, isQuotedAudio) => {  
try{  
var gombal = [
"Aku bahagia memilih berjalan denganmu. Aku rela untuk berjalan jauh asalkan selalu memegang tanganmu",
"Apa bedanya cincin sama kamu? Kalau cincin melekat di jari, kalau kamu melekat di hati aku",
"Aku rela ikut lomba lari keliling dunia, asalkan engkau yang menjadi garis finishnya",
"Mungkin aku kiper terburuk sedunia, membiarkan kamu membobol gawang berkali-kali dengan cintamu",
"Kata orang nyasar itu rugi banget, tapi aku nggak ngerasa rugi karena cintaku sudah nyasar ke hati bidadari",
"Jika kamu berdiri di depan cermin memegang 11 mawar, kamu akan melihat 12 bunga tercantik yang pernah ada",
"Sejak mengenalmu, bawaannya aku pengen belajar terus. Belajar menjadi yang terbaik buat kamu",
"Aku sukanya sih apel dibandingkan anggur, makanya aku suka ngapelin kamu ketimbang nganggurin kamu",
"Aku mau cinta kita seperti pelajaran sejarah yang selalu dikenang sampai akhir hayat",
"Hari Minggu itu weekend, tapi kalau cinta aku ke kamu tuh will never end",
"Kamu adalah orang pertama yang mampu membuat jantungku berdetak lebih lambat dan lebih cepat pada saat yang sama",
"Kamu memang seperti lempeng bumi, bergeser sedikit saja sudah mengguncang hatiku",
"Cinta aku ke kamu itu seperti kecoa, tidak akan punah dimakan oleh waktu",
"Kamu adalah terang yang akan selalu menyinari hatiku. Tanpamu hidupku kosong dan tidak ada apa-apanya",
"Kalau disuruh melupakanmu, aku akan ke kelurahan dulu. Minta surat keterangan tidak mampu",
"Orang kurus itu setia, makan aja tidak pernah tambah apalagi pasangan",
"Abjad dimulai dengan ABC, angka dimulai dengan 123. Lagu dimulai dengan do re mi. Cinta dimulai dengan aku dan kamu",
"Cintaku tulus seputih melati, masih engkau meragukannya? Jika ya, haruskah kurendam hatiku dengan So Klin Pemutih?",
"Selain ada garuda di dadaku, di dadaku juga selalu ada kamu",
"Cinta itu ibarat lingkaran yang tidak ada titik lainnya. Aku harap, kita tetap menjadi lingkaran sampai maut yang memisahkan",
"Aku tanpa kamu tuh bagaikan motor tanpa roda",
"Setiap melihat senyumanmu aku dapat merasakan hangatnya matahari. Setiap melihatmu tertawa aku seperti melihat indahnya bintang",
"Kamu tau gak apa persamaannya kamu sama AC? Sama-sama bikin aku sejuk",
"Aku mohon jangan jalan-jalan terus di pikiranku, duduk yang manis di hatiku saja",
"Gimana aku bisa tidur kalau jam segini kamu masih nongkrong di pikiranku",
"Napas aku kok sesek banget ya?, karena separuh nafasku ada di kamu",
"Jika kamu tanya berapa kali kamu datang ke pikiranku, jujur saja, cuma sekali. Habisnya, nggak pergi-pergi sih!",
"Cowok boleh nggak sih minum jamu sari rapet, soalnya aku mau rapetin hati aku ke hati kamu",
"Ketika kau mencintainya dan kau hanya mendapat hujan, cintailah aku sebagai pelangimu",
"Kamu kenal mama papaku gak? Kalau belum kenal, besok aku ajak kamu buat kenalan sama mama papaku",
"Kopi apa yang paling manis? Kopinang kau dengan bismillah",
"Kamu punya lem nggak? Aku mau pake untuk nge-lem hati kita biar bisa bersatu",
"Ikan apa yang bikin baper? Ikan stop loving you",
"Apa bedanya kamu sama jam 12 siang? Kalau jam 12 siang itu kesiangan, kalau kamu itu kesayangan",
"Kos apa yang paling bikin betah? Bikos I love you",
"Mukamu kayak orang susah ya, maksudnya susah untuk dilupain",
"Apa bedanya kamu sama barista? Barista mengaduk-aduk kopi susu, kalau kamu mengaduk-aduk hatiku",
"Namamu Dewi ya? Dewinner of my heart",
"Aku dan kamu itu bagaikan laptopku dan wifi cafe depan rumah. Udah auto connect",
"Selain cuci tangan, kamu tuh harus sering-sering cuci kaki juga. Soalnya telapak kaki kamu kan bakalan jadi surga untuk anak-anak kita nanti",
"Keluar dari rumah memang tidak dianjurkan, tapi yang benar-benar tidak bisa kamu lakukan adalah keluar dari pikiranku",
"Kangen kamu tuh kayak pas balon hijau meledak. Bikin hatiku sangat kacau",
"Nama kamu Dea ya? Deanswer to my prayer",
"Kenalin, namaku Dion. Donly man for you",
"Kamu pasti di masa depan bakalan suka nasi deh, nasihatin anak kita berdua",
"Cintaku ke kamu tuh kayak WA hoax dari emak-emak, pokoknya gak ada habisnya",
"Kipas apa yang aku tunggu? Kipastian dari kamu",
"Mie apa yang lebih nyenengin dari Indomie? Mielikin kamu",
"Kamu tuh kayak delman di kota pada hari Minggu, istimewa",
"Kotak apa yang menyakitkan? Kotak sadar ku telah mencintaimu",
"Hati-hati kemakan ombak, kamu cukup kemakan rayuanku aja",
"Kamu itu pensil warna ya? Soalnya kamu mewarnai hari-hariku",
"Apa perbedaan Saturnus sama kamu? Kalau saturnus cincinnya dari asterois, kalau kamu nanti cincinnya dari aku",
"Kalau kamu itu upil, aku adalah jari kelingking, mencari kamu sampai dapat",
"Apa perbedaan pizza sama kamu? Pizza buat cibagi-bagi, kalau kamu buat aku seorang diri",
"Tau gak perbedaan Mangga Dua sama kamu? Mangga Dua itu pusat perbelanjaan, kalau kamu itu pusat perhatianku",
"Ibukota boleh pindah ke Kalimantan, asalkan kamu jangan pindah ke Hatimantan",
"Aku suka segala macam berry, ada strawberry, blueberry, rasberry. Tapi favoritku tetap kauberry hatimu ke aku",
"Apa perbedaan bendera sama kamu? Kalau bendera berkibar di tiang, kalau kamu berkibar dihatiku",
"Namaku Jaelani, nama panjangnya, Jaelani aja dulu siapa tau nyaman",
"Apa perbedaan nelayan sama kamu? Kalau nelayan memancing ikan, kalau kamu memancing perhatianku",
"Berbagi santap sama kamu aja senang, apalagi berbagi atap?",
"Kamu tau gak bedanya kamu sama buku? Kalau kamu gudangnya ilmu, kalau kamu gudangnya rindu",
"Hasil polling yang tak pernah salah adalah polling in love with you",
"Kamu pasti Jawa ya? Jawaban doaku",
"Namamu bagus, tapi lebih bagus lagi kalau ada di kartu keluargaku",
"Apa bedanya kamu dan polisi lalu lintas? Kalau polisi mengalihkan lalu lintas, kalau kamu mengalihkan duniaku",
"Apa bedanya Bali sama kamu? Kalau Bali itu tujuan wisata, kalau kamu itu tujuan hidup",
"Apa bedanya Borobudur sama kamu? Kalau Borobudur itu candi, kalau kamu itu candu",
"Aku rela dipenjara seumur hidup, asalkan pelanggarannya karena mencintaimu",
"Cintaku padamu seperti utang. Awalnya kecil, didiemin, tau-tau gede sendiri",
"Kalau hitungan satu sampai sepuluh, cintaku cukup nomor dua, yaitu dualem banget",
"Aku setuju-setuju aja kok kalau harga BBM makin mahal, asalkan senyum kamu tetap murah sama aku",
"Biarkan waktu yang membuatku lelah dengan sendirinya karena merindukanmu",
"Sayang, kamu itu seperti garam di lautan, tidak terlihat namun akan selalu ada untuk selamanya",
"Meskipun kurus, kamu adalah hal terberat yang ada di hatiku",
"Semua bintang berkilauan, tapi hanya satu yang paling bercahaya. Itulah dirimu, sayangku",
"Masalah yang selalu sulit untukku membuatmu mencintaiku, tapi lebih sulit memaksa hatiku untuk berhenti memikirkan dirimu",
"Kamu tahu gak bedanya kamu sama daun? Kalau daun jatuhnya ke tanah, kalau kamu jatuhnya ke hatiku",
"Kalau kamu jadi senar gitar, aku nggak mau jadi gitarisnya. Karena aku nggak mau mutusin kamu",
"Kamu tahu apa persamaan rasa sayangku ke kamu dengan matahari? Persamaannya adalah sama-sama terbit setiap hari dan hanya akan berakhir sampai kiamat",
"Cara termudah yang aku lakukan untuk membuat senyuman di bibirku adalah dengan memejamkan mata, lalu mengingat senyum manismu",
"Jepang bikin robot. Jerman bikin mobil. Kamu bikin kangen",
"Aku kerja keras, sebab aku sadar untuk menghalalkanmu tidak cukup hanya dengan cinta",
"Jangan GR deh. Aku kangen kamu sedikit aja kok. Sedikit berlebihan maksudnya",
"Aku ingin bersamamu hanya dalam 2 waktu, yaitu sekarang dan selamanya",
"Yang kamu lihat di kulkas, itu bukan hati sapi. Itu hatiku yang beku karena ditinggal kamu",
"Ngemil apa yang paling enak? Ngemilikin Kamu sepenuhnya",
"Kalau bus kota jauh dekat ongkosnya sama, tapi cinta ini dekat-dekat makin saling cinta",
"Kamu itu sama seperti Ujian Nasional. Sama-sama harus diperjuangkan karena menyangkut masa depan",
"Berulang tahun memang indah. Akan tetapi lebih indah jika berulang kali bersamamu",
"Rumah joglo ada di Jogja, kalau kamu jomblo kabarin ya",
"Orang tuamu pengrajin bantal yah? Karena terasa nyaman jika di dekatmu",
"Kalau kuliah butuh skripsi, kalau kita cuma perlu resepsi",
"Kalau naik motor sama kamu pasti ditilang deh. Soalnya kita kan bertiga, aku, kamu, dan cinta",
"Anjing menggonggong kafilah berlalu, tiap hari bengong mikirin kamu melulu",
"Aku harap kamu tidak menanyakan hal terindah yang pernah singgah di kehidupanku, karena jawaban nya adalah kamu",
"Malam minggu paling menyenangkan menghitung bintang bersama kamu. Soalnya dengan cara itu, aku bisa lebih lama bersama kamu",
"Tak perlu risau jika besok adalah malam ahad, lebih baik tetap istiqomah sampai malam akad",
"Semoga kita semua dijauhkan dari virus dan didekatkan dengan yang serius",
"Selamat kamu menang penghargaan cerita terbaik. Sejak ada kamu, cerita hidupku menjadi indah",
"Kalau ada lampu jangan cari lilin, kalau ada aku jangan cari yang lain",
"Tahukah sebatas apa cintaku padamu? Pergilah ke tengah lautan luas. Jika mata bisa melihat batas laut di sana, artinya kau telah melihat batas cintaku",
"Ini hatiku, hati yang tak pernah mengeluh untuk terus mengagumimu",
"Aku bukanlah yang sempurna, tapi aku bersyukur karena memilikimu yang melengkapi ketidaksempurnaan ini",
"Hal tersulit bagiku adalah melupakanmu karena buat ngelupain kamu sama sulitnya dengan mengingat seseorang yang tak pernah kukenal",
"Jika kita ditakdirkan untuk bersama, aku tak ingin hanya janji dan kata setia darimu karena cinta butuh kepastian yang nyata",
"Mungkin di dunia ini aku sudah ditakdirkan buta. Maksudku, buta untuk melihat wanita lain selain kecantikan yang ada pada dirimu",
"Ada lampu merah gak? Keliatannya aku butuh, soalnya deket kamu nyamannya suka kelewatan",
"Makanan yang paling melambangkan perasaanku ke kamu itu gudeg. Gu deg degan kalau ketemu kamu",
"Jangankan memilikimu, mendengar kamu kentut aja aku sudah bahagia",
"Berulang tahun memang indah, namun bagiku yang lebih indah jika berulang kali bersamamu",
"Kesasar itu serasa rugi banget, namun aku nggak merasa rugi karena cintaku sudah kesasar ke hatimu",
"Ada 3 hal yang paling aku sukai di dunia ini, yaitu matahari, bulan dan kamu. Matahari untuk siang hari, bulan untuk malam hari, dan kamu untuk selamanya di hatiku",
"Aku tidak peduli ramalan BMKG, sebab saat hujan, badai bahkan tsunami aku akan tetap bertahan pada cintamu",
"Kamu itu seperti garam di lautan, tidak terlihat namun akan selalu ada untuk selamanya",
"Cintaku padamu seperti ban kereta api, tidak pernah kempes",
"Aku rela dipenjara asalkan pelanggarannya karena mencintaimu",
"Aku ingin kita seperti sandal jepit sebab hanya ada dua, tidak ada yang namanya orang ketiga",
"Tuhan itu baik yah. Saat aku minta bunga mawar, aku diberi taman yang indah. Saat aku meminta setetes air, aku diberi lautan. Eh, saat aku minta malaikat, aku diberi kamu",
"Jika kau memegang 7 bunga mawar di depan cermin, maka kau adalah mawar ke-8 yang terindah di seluruh dunia",
"Kamu memang seperti lempeng bumi, bergeser sedikit saja sudah mengguncang hatiku",
"Kata dimulai dengan ABC, angka dimulai dengan 123. Lagu dimulai dengan do re mi. Cinta dimulai dengan aku dan kamu",
"Kalau hitungan satu sampai sepuluh, cintaku cukup nomor dua, yaitu dualem banget",
"Jepang bikin robot. Jerman bikin mobil. Kamu bikin kangen",
"Tanggal merah sekalipun aku tidak libur untuk memikirkan kamu",
"Aku rela jadi abang nasi goreng asalkan setiap malam aku bisa lewat depan rumah kamu",
"Handphone saja sanggup simpan foto sampai beribu-ribu, masa hanya untuk menyimpan aku, hati kamu nggak sanggup sih",
"Walaupun jarak kita bagai Matahari dan Pluto saat ephehelium. Amplitudo gelombang hatimu berintervensi dengan hatiku",
"Orang kurus itu setia, tambah makan aja tidak pernah tambah apalagi pasangan"
]

md.sendMessage(from, { text: gombal[Math.floor(Math.random() * gombal.length)], mentions: [sender]}, {quoted: md1})
} catch (e) { console.log(e) }
} 
